### ISSUE TITLE
leaving the heat tape on longer

### ISSUE THREAD

**Issue by pcjer** [erisod/heattape-smartthings#2]
Hi, first off, this app is extremely helpful.  I'm in a very dry climate where we get lots of snow for relatively little water content.  So I've modified the snow melt down to 1.6, and since the heat tape is only on the north side of the house that sees basically no sun in winter I reduced the impact of the sun factor to 1.0.  Also, I've increased the weather history from 4 to 10 so that hopefully the heat tape stays on longer when it was already on and had a freezing temp in the past 10 hours instead of 4.  I also removed the part where the heat tape stays on if there is snow on the ground at all because in the winter here there will be snow from November through April on the ground.

What I can't seem to figure out is how to increase the time the heat tape would stay on after snow.  I am assuming it would be relatively easy in the logic around if the weather says snow but is not showing accumulation.  Every time I try to modify the argument I get an error when I try to publish the code though.  Basically what I want to accomplish is that if the weather data says it was snowing at all in the past 10 hours leave the heat tape on even if everything else is false.  

Any ideas?

**Comment by erisod** [comment]
I'm glad you're finding it useful.   I haven't looked at this code
seriously for awhile.

I find, for myself, it's useful to review the purpose of heat tape when
I've worked on this stuff:  It's functional in conditions where snow melts
on the roof (usually from interior heating but could be sun), and melt
water runs into gutters but the air temperature is such that the water
freezes in the gutters, creating a backup.   It's not useful if there isn't
water running, nor if the water doesn't re-freeze.

If you have so much snow accumulating that you really only care about the
temperature you can use the temperature only mode.  That works similarly to
those little heat-tape control blocks.

If the air isn't *currently* freezing (or close) it's not clear to me why
you'd want to run your heat tape (maybe it's so much colder on the shaded
side of your house that it continues to freeze when the air temp is above
freezing?), but I can make a suggestion about how to accomplish this in the
software:

You can modify the InTempRange() function and in instances where getTemp()
is called use getMinTemp(10) instead -- this will return the lowest
temperature in the last 10 recordings.  The other logic can remain the
same.

Regarding getting an error when you push the code, I'd need to see the
error and specifically what're you're doing to help there.

Good luck!!
